title: freestruct
description: SEO layer for static doc sites
url: http://freestruct.creadev.org
baseurl:

# Theme
theme: null
plugins:
  - jekyll-sitemap

# Search
search:
  provider: pagefind

# Navigation
nav:
  - title: Home
    url: /
  - title: Getting Started
    url: /getting-started
  - title: Configuration
    url: /configuration
  - title: ssr-config.yml
    url: /ssr-config

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty

# Sass
sass:
  sass_dir: assets/scss
  style: compressed

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: page